/**
 * Imports the IU self-service model catalog from a saved HTML export of the
 * model-list view (https://ue-self-service.app.iu-it.org/check-key).
 *
 * The portal is a Blazor Server app behind SSO, so the catalog can't be fetched
 * programmatically — re-export the page's HTML when IU changes and re-run this.
 *
 *   bun run scripts/import-portal.ts [path-to-export.html]
 *
 * It writes a committed catalog snapshot (src/db/iu-catalog.ts) and upserts the
 * models into the database.
 */
import { readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { eq, sql } from "drizzle-orm";
import { parsePortalHtml } from "../src/server/iu/portal.js";
import { db, client } from "../src/db/index.js";
import { models } from "../src/db/schema.js";

const htmlPath = process.argv[2] ?? join(homedir(), "Downloads", "models.html");
const html = await readFile(htmlPath, "utf-8");
const catalog = parsePortalHtml(html);

if (catalog.length === 0) {
  console.error(`[import-portal] no models parsed from ${htmlPath}`);
  await client.end();
  process.exit(1);
}

const byModality = catalog.reduce<Record<string, number>>((acc, m) => {
  acc[m.modality] = (acc[m.modality] ?? 0) + 1;
  return acc;
}, {});
console.log(`[import-portal] parsed ${catalog.length} models from ${htmlPath}`);
console.log(`[import-portal] by modality:`, byModality);

// Write committed snapshot so seeding/tests/deploy don't depend on the HTML file.
const fileBody =
  `// AUTO-GENERATED by scripts/import-portal.ts from the IU self-service model-list export.\n` +
  `// Do not edit by hand — re-run \`bun run scripts/import-portal.ts <export.html>\` to refresh.\n` +
  `import type { ModelInsert } from "./schema.js";\n\n` +
  `export const IU_CATALOG: ModelInsert[] = ${JSON.stringify(catalog, null, 2)};\n`;
const outFile = join(import.meta.dirname, "../src/db/iu-catalog.ts");
await writeFile(outFile, fileBody);
console.log(`[import-portal] wrote ${outFile}`);

await db
  .insert(models)
  .values(catalog)
  .onConflictDoUpdate({
    target: models.id,
    set: {
      provider: sql`excluded.provider`,
      family: sql`excluded.family`,
      modality: sql`excluded.modality`,
      display_name: sql`excluded.display_name`,
      context_window: sql`excluded.context_window`,
      iu_listed: sql`excluded.iu_listed`,
    },
  });
console.log(`[import-portal] upserted ${catalog.length} models into the database`);

// Remove any leftover non-portal rows (e.g. the old fictional seed). Probes,
// metrics and demos referencing them cascade-delete via FK constraints.
const removed = await db
  .delete(models)
  .where(eq(models.iu_listed, false))
  .returning({ id: models.id });
if (removed.length > 0) {
  console.log(`[import-portal] removed ${removed.length} stale non-portal models`);
}

await client.end();
