/**
 * Imports the IU gateway's Replicate speech-model catalog (TTS/STT only — LLM
 * and image models on Replicate duplicate the IU-native catalog).
 *
 *   bun run scripts/import-replicate.ts
 *
 * It writes a committed catalog snapshot (src/db/replicate-catalog.ts) and
 * upserts the models into the database.
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { sql } from "drizzle-orm";
import { fetchReplicateCatalog, classifyReplicateModality } from "../src/server/iu/replicate.js";
import { prettifyName } from "../src/server/iu/discover.js";
import { db, client } from "../src/db/index.js";
import { models } from "../src/db/schema.js";
import type { ModelInsert } from "../src/db/schema.js";

const raw = await fetchReplicateCatalog();

const catalog: ModelInsert[] = raw.flatMap((m) => {
  const modality = classifyReplicateModality(m);
  if (!modality) return [];
  return [
    {
      id: m.id,
      provider: (m.id.includes("/") ? m.id.split("/")[0] : m.id) ?? "other",
      family: null,
      modality,
      display_name: prettifyName(m.id),
      context_window: null,
      iu_listed: true,
      transport: "replicate",
    } satisfies ModelInsert,
  ];
});

if (catalog.length === 0) {
  console.error(`[import-replicate] no speech models parsed from the Replicate catalog`);
  await client.end();
  process.exit(1);
}

const byModality = catalog.reduce<Record<string, number>>((acc, m) => {
  acc[m.modality] = (acc[m.modality] ?? 0) + 1;
  return acc;
}, {});
console.log(`[import-replicate] parsed ${catalog.length} speech models from ${raw.length} official`);
console.log(`[import-replicate] by modality:`, byModality);

// Write committed snapshot so seeding/tests/deploy don't depend on a live call.
const fileBody =
  `// AUTO-GENERATED by scripts/import-replicate.ts from the IU gateway's Replicate route.\n` +
  `// Do not edit by hand — re-run \`bun run scripts/import-replicate.ts\` to refresh.\n` +
  `import type { ModelInsert } from "./schema.js";\n\n` +
  `export const REPLICATE_CATALOG: ModelInsert[] = ${JSON.stringify(catalog, null, 2)};\n`;
const outFile = join(import.meta.dirname, "../src/db/replicate-catalog.ts");
await writeFile(outFile, fileBody);
console.log(`[import-replicate] wrote ${outFile}`);

await db
  .insert(models)
  .values(catalog)
  .onConflictDoUpdate({
    target: models.id,
    set: {
      provider: sql`excluded.provider`,
      family: sql`excluded.family`,
      modality: sql`excluded.modality`,
      display_name: sql`excluded.display_name`,
      context_window: sql`excluded.context_window`,
      iu_listed: sql`excluded.iu_listed`,
      transport: sql`excluded.transport`,
    },
  });
console.log(`[import-replicate] upserted ${catalog.length} models into the database`);

await client.end();
