/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TtsRouteImport } from './routes/tts'
import { Route as SttRouteImport } from './routes/stt'
import { Route as StackRouteImport } from './routes/stack'
import { Route as NewsRouteImport } from './routes/news'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TtsRoute = TtsRouteImport.update({
  id: '/tts',
  path: '/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const SttRoute = SttRouteImport.update({
  id: '/stt',
  path: '/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/news': typeof NewsRoute
  '/stack': typeof StackRoute
  '/stt': typeof SttRoute
  '/tts': typeof TtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/news': typeof NewsRoute
  '/stack': typeof StackRoute
  '/stt': typeof SttRoute
  '/tts': typeof TtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/news': typeof NewsRoute
  '/stack': typeof StackRoute
  '/stt': typeof SttRoute
  '/tts': typeof TtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/catalog' | '/news' | '/stack' | '/stt' | '/tts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/catalog' | '/news' | '/stack' | '/stt' | '/tts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/news'
    | '/stack'
    | '/stt'
    | '/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  NewsRoute: typeof NewsRoute
  StackRoute: typeof StackRoute
  SttRoute: typeof SttRoute
  TtsRoute: typeof TtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tts': {
      id: '/tts'
      path: '/tts'
      fullPath: '/tts'
      preLoaderRoute: typeof TtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stt': {
      id: '/stt'
      path: '/stt'
      fullPath: '/stt'
      preLoaderRoute: typeof SttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  NewsRoute: NewsRoute,
  StackRoute: StackRoute,
  SttRoute: SttRoute,
  TtsRoute: TtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
