/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TtsRouteImport } from './routes/tts'
import { Route as SttRouteImport } from './routes/stt'
import { Route as StackRouteImport } from './routes/stack'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as IndexRouteImport } from './routes/index'

const TtsRoute = TtsRouteImport.update({
  id: '/tts',
  path: '/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const SttRoute = SttRouteImport.update({
  id: '/stt',
  path: '/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/benchmarks': typeof BenchmarksRoute
  '/catalog': typeof CatalogRoute
  '/stack': typeof StackRoute
  '/stt': typeof SttRoute
  '/tts': typeof TtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/benchmarks': typeof BenchmarksRoute
  '/catalog': typeof CatalogRoute
  '/stack': typeof StackRoute
  '/stt': typeof SttRoute
  '/tts': typeof TtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/benchmarks': typeof BenchmarksRoute
  '/catalog': typeof CatalogRoute
  '/stack': typeof StackRoute
  '/stt': typeof SttRoute
  '/tts': typeof TtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bench'
    | '/benchmarks'
    | '/catalog'
    | '/stack'
    | '/stt'
    | '/tts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bench' | '/benchmarks' | '/catalog' | '/stack' | '/stt' | '/tts'
  id:
    | '__root__'
    | '/'
    | '/bench'
    | '/benchmarks'
    | '/catalog'
    | '/stack'
    | '/stt'
    | '/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchRoute: typeof BenchRoute
  BenchmarksRoute: typeof BenchmarksRoute
  CatalogRoute: typeof CatalogRoute
  StackRoute: typeof StackRoute
  SttRoute: typeof SttRoute
  TtsRoute: typeof TtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tts': {
      id: '/tts'
      path: '/tts'
      fullPath: '/tts'
      preLoaderRoute: typeof TtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stt': {
      id: '/stt'
      path: '/stt'
      fullPath: '/stt'
      preLoaderRoute: typeof SttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchRoute: BenchRoute,
  BenchmarksRoute: BenchmarksRoute,
  CatalogRoute: CatalogRoute,
  StackRoute: StackRoute,
  SttRoute: SttRoute,
  TtsRoute: TtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
